### ISSUE TITLE
can not run rkeel 

### ISSUE THREAD

**Issue by zengqing1** [i02momuj/RKEEL#3]
hi，
When I installed the RKEEL, it seems everthing was ok. But when I tried to run some example in the help page, it always said  the fellowing message 
----
Error! Error in private$readOutputs(paste0(private$mainPath, "/results/", private$algorithmName, : Results were not stored. Execution error.

----
For example , when I run the fellowing code and I got

> data_train <- RKEEL::loadKeelDataset("autoMPG6_train")
D:/R/R-3.5.2/library/RKEELdata/datasets/> data_test <- RKEEL::loadKeelDataset("autoMPG6_test")
D:/R/R-3.5.2/library/RKEELdata/datasets/> 
> #Create algorithm
> algorithm <- RKEEL::CART_R(data_train, data_test)
> 
> #Run algorithm
> algorithm$run()
C:/Users/ADMINI~1/AppData/Local/Temp/RtmpyMbpBn/experiment_2019-12-13_20-03-532325/results/CART-R.data/result0.tra
C:/Users/ADMINI~1/AppData/Local/Temp/RtmpyMbpBn/experiment_2019-12-13_20-03-532325/results/CART-R.data/result0.tst
Error! Error in private$readOutputs(paste0(private$mainPath, "/results/", private$algorithmName, : Results were not stored. Execution error.
> 

And if I  tried anthor example code , the result was the same.
I checked the temp directory RtmpyMbpBn, there was not experiment_2019-12-13_20-03-532325.
So , why?  Is there some configuration needed set by me?

----
> R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo              
> 
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] arules_1.6-4  pmml_2.1.0    XML_3.98-1.20 Matrix_1.2-17 RKEEL_1.3.1  

loaded via a namespace (and not attached):
 [1] lattice_0.20-38   codetools_0.2-16  gtools_3.8.1      digest_0.6.22     foreach_1.4.7     grid_3.5.2        R6_2.4.1         
 [8] magrittr_1.5      stringi_1.4.3     RKEELdata_1.0.5   gdata_2.18.0      doParallel_1.0.15 iterators_1.0.12  tools_3.5.2      
[15] stringr_1.4.0     downloader_0.4    RKEELjars_1.0.19  parallel_3.5.2    compiler_3.5.2    rJava_0.9-11     

----

zeng qing

**Comment by i02momuj** [comment]
Hi Zeng,

This issue should have been fixed in last version of RKEEL (1.3.1), which if I'm not wrong is the version you are using. I have been now executing the same code under the 3.5.2 version of R and Windows 10 and it executes correctly, so I have to investigate what is happening.

On the other hand, the fact that the folder of the experiment does not exist is because RKEEL automatically removes them unless other specified, in order to not to keep trash directories.
You can try to execute the algorithm indicating the path where you want to create the experiments folder (`algorithm$run(folderPath = "..."`), and/or an unique folder name for the experiment (`algorithm$run(expUniqueName= "..."`). Using any of these two options, you should be able to explore the experiment folder and see what is happening.

Please, could you explore the experiment folder and check if the following statements are correct? Could you report me if any of the files that are following presented is not included in your experiment folder?

- Inside the 'datasets/data' folder there are two files called train.dat and test.dat
- Inside the 'exe' folder, there are a file called 'Regr-CART.jar' (if CART method is being executed).
- Inside the 'scripts/CART-R/data' folder there exist a file called 'config0s0.txt'.

**Comment by zengqing1** [comment]
hi,
 Thank your response.

 After I uninstalled the Java all in my computer,  I installed the Java 8 and Java 11 jdk, and reinstall Java 11 again , then it is ok.

zeng qing

**Comment by zengqing1** [comment]
hi
And The files and directory you mentioned all existed.

**Comment by i02momuj** [comment]
Perfect. So I close the issue as it has been solved.
